name: Deploy Terraform Infra

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environnement à déployer"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - preprod
          - prod

  push:
    branches:
      - staging
      - preprod
      - prod

permissions:
  id-token: write # pour OIDC
  contents: read # pour checkout le repo

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || github.ref_name }}

    steps:
      # 1️⃣ Checkout du repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configurer AWS via OIDC
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: github-actions-terraform

      # 3️⃣ Installer  Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # 4️⃣ Initialiser Terraform
      - name: Terraform Init
        run: terraform init

      # 5️⃣ Déterminer l'environnement et le fichier .tfvars
      - name: Set ENV
        id: set_env
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          else
            echo "ENV=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          fi
          echo "Using environment: $ENV"

      # 6️⃣ Sélectionner ou créer le workspace Terraform correspondant
      - name: Select Terraform Workspace
        run: |
          terraform workspace select -or-create $ENV

      # 7️⃣ Plan Terraform avec le tfvars correct
      - name: Terraform Plan
        run: terraform plan -var-file="envs/${ENV}/${ENV}.tfvars" -out=tfplan

      # 8️⃣ Apply Terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      # 9️⃣ Afficher les outputs
      - name: Show Terraform Outputs
        run: terraform output -json
