name: Deploy Terraform Infra

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environnement à déployer"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - preprod
          - prod

  push:
    branches:
      - staging
      - preprod
      - prod

permissions:
  id-token: write # pour OIDC
  contents: read # pour checkout le repo

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || github.ref_name }}

    steps:
      # 1️⃣ Checkout du repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configurer AWS via OIDC
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_ARN }}
          aws-region: ${{secrets.AWS_REGION}}
          role-session-name: github-actions-terraform

      # 3️⃣ Installer Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # 4️⃣ Initialiser Terraform
      - name: Terraform Init
        run: terraform init

      # 5️⃣ Déterminer le fichier .tfvars à utiliser
      - name: Set TFVARS
        id: set_tfvars
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          else
            # Pour push automatique, on récupère le nom de la branche
            echo "ENV=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          fi
          echo "Using environment: $ENV"

      # 6️⃣ Plan Terraform
      - name: Terraform Plan
        run: terraform plan -var-file="${ENV}.tfvars" -out=tfplan

      # 7️⃣ Apply Terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      # 8️⃣ Afficher les outputs
      - name: Show Terraform Outputs
        run: terraform output -json
